# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0004_auto_20170602_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
